### PR TITLE
Remove maintenance tag from the `SlurmQueueStatusCheck` check

### PR DESCRIPTION
**Pull request by rsarm**

### CODE REVIEW

**Comment by lucamar** [comment]
The test failed on `hohgant`:
```
[     FAIL ] (2/2) MemoryOverconsumptionMpiCheck /6a7583af @hohgant:gpu+PrgEnv-cray

P: max_cn_memory: 500 GB (r:0, l:None, u:None)

P: max_allocated_memory: 251 GB (r:500, l:-0.05, u:None)

==> test failed during 'performance': test staged in '/scratch/e1000/jenscscs/ci-cscs-reframe-tests-hohgant-396b0f8-103/reframe/stage/hohgant/gpu/PrgEnv-cray/MemoryOverconsumptionMpiCheck'
```

**Review by lucamar — APPROVED** [review]
Thanks @rsarm

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by teojgo** [comment]
> The test failed on `hohgant`:
> 
> ```
> [     FAIL ] (2/2) MemoryOverconsumptionMpiCheck /6a7583af @hohgant:gpu+PrgEnv-cray
> P: max_cn_memory: 500 GB (r:0, l:None, u:None)
> P: max_allocated_memory: 251 GB (r:500, l:-0.05, u:None)
> 
> ==> test failed during 'performance': test staged in '/scratch/e1000/jenscscs/ci-cscs-reframe-tests-hohgant-396b0f8-103/reframe/stage/hohgant/gpu/PrgEnv-cray/MemoryOverconsumptionMpiCheck'
> ```

This https://github.com/eth-cscs/cscs-reframe-tests/pull/30 fixes the hohgant issue.

**Comment by ekouts** [comment]
@jenkins-cscs retry none

**Pull request merged**
