### PR TITLE
Update tolerance of MemoryOverconsumptionMpiCheck

### PR DESCRIPTION
**Pull request by lucamar**
The test `MemoryOverconsumptionMpiCheck` often [fails to meet the expected performance](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-pilatus-production-daily/detail/reframe-pilatus-production-daily/993/pipeline) with `PrgEnv-cray` and `PrgEnv-gnu` on Pilatus with CPE 23.12 and COS 3.0. 
I suggest to increase the tolerance to 10% below the reference value, which will make the test pass on Pilatus as well.

### CODE REVIEW

**Comment by lucamar** [comment]
The testing stage on Dom and Piz Daint failed with the following error:
```
ERROR: you must specify -C with one of the following: mc,gpu,ssd
sbatch: error: cli_filter plugin terminated with error
```

**Comment by lucamar** [comment]
The `Testing` phase of the CI is failing on Dom and Piz Daint with the error message:
```
ERROR: you must specify -C with one of the following: mc,gpu,ssd
sbatch: error: cli_filter plugin terminated with error
```
The failure of `SlurmQueueStatusCheck` on Eiger is due to some unavailable compute nodes.

**Comment by lucamar** [comment]
I have submitted [SD-61887](https://jira.cscs.ch/browse/SD-61887) on behalf of a user about the less memory available on compute nodes after the system upgrade.

**Review by jgphpc — APPROVED** [review]
more details in [SD-61887](https://jira.cscs.ch/browse/SD-61887)

**Comment by jgphpc** [comment]
@jenkins-cscs test this

**Pull request merged**
