### PR TITLE
Add Cuda nvml check for uenv

### PR DESCRIPTION
**Pull request by jgphpc**
https://jira.cscs.ch/browse/VCUE-50

Tested with:
```
UENV_FILE=/scratch/e1000/manitart/myimages/nvhpc_a100.squashfs \
RFM_CONFIG=~/cscs-reframe-tests.git/config/cscs-uenv.py \
~/R --system hohgant:nvgpu -r -c uenv_checks/prgenv/cuda_nvml.py
```

### CODE REVIEW

**Review by teojgo — CHANGES_REQUESTED** [review]
Can you adapt it to make sure that all the devices are reported? You can use the Mixin for the cuda available devices.

**Comment by jgphpc** [comment]
> Can you adapt it to make sure that all the devices are reported? 

The code calls [nvmlDeviceGetCount](https://developer.download.nvidia.com/compute/DevZone/NVML/doxygen/group__group4.html#g15d2e66be566e6a0e02734b9fd1d3446) -> all the devices are being reported, CUDA_VISIBLE_DEVICES is ignored.

**Comment by teojgo** [comment]
> > Can you adapt it to make sure that all the devices are reported?
> 
> The code calls [nvmlDeviceGetCount](https://developer.download.nvidia.com/compute/DevZone/NVML/doxygen/group__group4.html#g15d2e66be566e6a0e02734b9fd1d3446) -> all the devices are being reported, CUDA_VISIBLE_DEVICES is ignored.

I mean in the sanity function to make sure that all the gpus are detected. Similar to https://github.com/eth-cscs/cscs-reframe-tests/blob/1862df2af902da0a69ac5f98bc5f54ce871054cc/checks/containers/buildah/buildah_check.py#L141

**Review by teojgo — APPROVED** [review]
Thanks, looks good now.

**Pull request merged**
